[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "whatsapp-server"

[services.variables]
NODE_ENV = "production"
PORT = "3001"
API_KEY = { generate = true }
